version: '3.8'
services:
  yb-master:
    image: yugabytedb/yugabyte:latest
    container_name: yb-master
    command: ["bin/yb-master", "--master_addresses=yb-master:7100", "--rpc_bind_addresses=yb-master:7100", "--fs_data_dirs=/mnt/disk0"]
    ports:
      - "7001:7000"
    environment:
      SERVICE_7000_NAME: yb-master
    volumes:
      - yb-master-data:/mnt/disk0

  yb-tserver-1:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-1
    command: ["bin/yb-tserver", "--tserver_master_addrs=yb-master:7100", "--rpc_bind_addresses=yb-tserver-1:9100", "--fs_data_dirs=/mnt/disk0"]
    ports:
      - "9042:9042"
      - "5433:5433"
    depends_on:
      - yb-master
    environment:
      SERVICE_5433_NAME: ysql
    volumes:
      - yb-tserver-1-data:/mnt/disk0
      - ./init:/init

  yb-tserver-2:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-2
    command: ["bin/yb-tserver", "--tserver_master_addrs=yb-master:7100", "--rpc_bind_addresses=yb-tserver-2:9100", "--fs_data_dirs=/mnt/disk0"]
    depends_on:
      - yb-master
    volumes:
      - yb-tserver-2-data:/mnt/disk0

  yb-tserver-3:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-3
    command: ["bin/yb-tserver", "--tserver_master_addrs=yb-master:7100", "--rpc_bind_addresses=yb-tserver-3:9100", "--fs_data_dirs=/mnt/disk0"]
    depends_on:
      - yb-master
    volumes:
      - yb-tserver-3-data:/mnt/disk0

  yb-init:
    image: yugabytedb/yugabyte:latest
    container_name: yb-init
    entrypoint: ["/bin/sh", "-c", "sleep 10 && bash /init/init.sh"]
    depends_on:
      - yb-tserver-1
    volumes:
      - ./init:/init
  yb-tserver-4:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-4
    command: ["bin/yb-tserver", "--tserver_master_addrs=yb-master:7100", "--rpc_bind_addresses=yb-tserver-4:9100", "--fs_data_dirs=/mnt/disk0"]
    depends_on:
      - yb-master
    volumes:
      - yb-tserver-4-data:/mnt/disk0

  yb-tserver-5:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-5
    command: ["bin/yb-tserver", "--tserver_master_addrs=yb-master:7100", "--rpc_bind_addresses=yb-tserver-5:9100", "--fs_data_dirs=/mnt/disk0"]
    depends_on:
      - yb-master
    volumes:
      - yb-tserver-5-data:/mnt/disk0

volumes:
  yb-master-data:
  yb-tserver-1-data:
  yb-tserver-2-data:
  yb-tserver-3-data:
  yb-tserver-4-data:
  yb-tserver-5-data:
